[theme]
theme = "modern"
[icons]
icons = "awesome6"

[[block]]
block = "toggle"
format = "$icon  |"
command_state = "ps -e | rg -i easyeffects"
command_on = "launch_eq.sh on"
command_off = "launch_eq.sh off"
interval = 1 

[[block]]
block = "toggle"
format = "$icon  |"
command_state = "bluetoothctl show | rg -i powered | awk -e '{if ($2 == \"yes\") {print 1}}'"
command_on = "bluetoothctl power on"
command_off = "bluetoothctl power off"
interval = 1

[[block]]
block = "music"
format ="$icon {$combo.str(max_w:35,rot_interval:0.5) $prev $play $next |}" 
interface_name_exclude = [".*kdeconnect.*", ".*firefox.*", ".*qutebrowser.*", ".*easyeffects.*", ".*vlc.*"]


[[block]]
block = "sound"
step_width = 5

[[block]]
block = "backlight"
format = "\uf042 $brightness"
invert_icons = true

[[block]]
block = "disk_space"
path = "/"
format = " $icon $available "
format_alt = " $icon $available / $total "
info_type = "available"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "net"
interval = 2

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "temperature"
interval = 2
format = " $icon "
format_alt = " $icon $average avg "
idle = 55
info = 65
chip = "coretemp-isa-0000"

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage "

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
short = " $icon $timestamp.datetime(f:%R) "
